# Generated by Django 2.2 on 2023-02-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='online/images')),
                ('username', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=35)),
                ('no_book_issued', models.IntegerField()),
                ('contact', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
            ],
        ),
    ]
